### ISSUE TITLE
Monthly setting doesn't consider changes in year

### ISSUE THREAD

**Issue by lmf-mx** [theohbrothers/Log-Rotate#48]
Using a setting of monthly in the config fails to rotate after the end of the year in which the task is deployed. Once December comes and is processed, the `if ($_now_dt.Month -gt $_last_dt.Month)` will always return false as the last run that was successful is always 12.

**Comment by leojonathanoh** [comment]
@lmf-mx Thanks for the bug report. i'll have to check it out.

**Comment by leojonathanoh** [comment]
@lmf-mx yeah there's insufficient unit tests, so it's one specific case, should it be then:

```powershell
if ( ($_now_dt.Month -gt $_last_dt.Month) -or ($_now_dt.Year -gt $_last_dt.Year -and $_last_dt.Month -eq 12) ) 
```

what do you think?

**Comment by leojonathanoh** [comment]
since weekly has something similar: https://github.com/theohbrothers/Log-Rotate/blob/v1.5.2/src/Log-Rotate/classes/New-LogObject.ps1#L712

**Comment by leojonathanoh** [comment]
@lmf-mx i'll open a PR to fix this, you can try out the PR, using `Import-Module src/Log-Rotate`.

**Comment by lmf-mx** [comment]
I would drop the check to see if the last month was 12.

`if ( ($_now_dt.Month -gt $_last_dt.Month) -or ($_now_dt.Year -gt $_last_dt.Year) ) `

This will cover situations where a server has downtime, is inactive, broken, etc. If the year changed, we're in a newer month than the last run and want to run, even if we turn our server back on in June instead of January.

**Comment by leojonathanoh** [comment]
@lmf-mx sounds like a plan. let me force push, you can try it out

**Comment by leojonathanoh** [comment]
@lmf-mx done, please let me know if it works

**Comment by leojonathanoh** [comment]
@lmf-mx this project hasn't had enough users, and i haven't had the time to write unit tests. really appreciate your bug report 😃

**Comment by leojonathanoh** [comment]
oops forgot to `return $true`, should be right now :)

**Comment by lmf-mx** [comment]
@leojonathanoh Need to put the final else back to tell the log that we're still in the same month.

**Comment by leojonathanoh** [comment]
@lmf-mx just did that sorry about that, i was rushing a bit :) fixed it in the last push

**Comment by lmf-mx** [comment]
@leojonathanoh Just ran it and it looks good. All my logs rotated. Next month will be fun when 33 month old logs compress. Started this task in March of 2019. Thanks!

**Comment by leojonathanoh** [comment]
@lmf-mx thanks much! hope the best for next month. i've used `compress` and it worked for me so i don't foresee any issue :)
