### ISSUE TITLE
"create" directive does not seem to work

### ISSUE THREAD

**Issue by GertVanderstukken** [theohbrothers/Log-Rotate#63]
Hey all,

is seems that the create directive inside a configuration file does not work.
It should create a new file with the original name after rotation, but that does not seem to work...
Here's my (simplified) config file:

C:\ProgramData\Update-EveryModule\Logs\Update-EveryModule_PowerShellCore.log {
    rotate 10
    daily
    create
}

Am I doing something wrong?
I somebody else using "create" ?

BTW: thanks for the great tool. It is helping me a lot...

**Comment by leojonathanoh** [comment]
Yes, it should do like you said. The integration tests show that it should work as expected https://github.com/theohbrothers/Log-Rotate/blob/master/src/Log-Rotate/Log-Rotate.Integration.Tests.ps1#L301-L324. 

So I'm not sure why it's happening.

**Comment by leojonathanoh** [comment]
Could you try removing `daily`, or ignore `daily` rotation by using `-Force`?

**Comment by GertVanderstukken** [comment]
Hmm. I see in the integration tests that you add some (linux related) parameters:
create 700 1000 1000

I will test that later this evening

**Comment by GertVanderstukken** [comment]
It seems that create needs a parameter (but I don't think it is used)...

This works:
C:\ProgramData\Update-EveryModule\Logs\Update-EveryModule_PowerShellCore.log {
  rotate 10
  daily
  create dummy
}

**Comment by leojonathanoh** [comment]
Good catch. I guess I'll push a fix for windows where those three optional parameters may not be supplied. :D

**Comment by leojonathanoh** [comment]
This will be fixed in v1.6.0. Thank you for the bug report :)

**Comment by GertVanderstukken** [comment]
Great, thanks for the quick action !
